apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminsystem
  labels:
    app: adminsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminsystem
  template:
    metadata:
      labels:
        app: adminsystem
    spec:
      containers:
        - name: adminsystem
          image: "a0717.azurecr.io/adminsystem3:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
